### ISSUE TITLE
Ingen nynorsk?

### ISSUE THREAD

**Issue by Havard-SL** [hackerspace-ntnu/statutter#1]
Alt er skriven på bokmål, kvifor ikkje nynorsk?

**Comment by gsorensen** [comment]
Ban Håvard from the repo

**Comment by torsteinnh** [comment]
Irellevant komentar, ingen er enige, lukkes.

**Comment by torsteinnh** [comment]
Rydder i lukkede issues

**Comment by Havard-SL** [comment]
:1984:

**Comment by torsteinnh** [comment]
Big bokmål er på saken
