### ISSUE TITLE
Legge til "eller ansatt"

### ISSUE THREAD

**Issue by CJGutz** [hackerspace-ntnu/statutter#10]
Endre "En pang har -- så lenge de er studenter ved NTNU -- fri tilgang "
til  "En pang har -- så lenge de er studenter eller ansatt ved NTNU -- fri tilgang "

**Comment by torsteinnh** [comment]
Hva med "-- så lengde de har nøkkelkort ved NTNU --"? Jeg hadde kun eksternkort i en periode.

**Comment by torsteinnh** [comment]
Fant endringen i de nye statuttene.
