### ISSUE TITLE
Legg til grense på antall fullmakter

### ISSUE THREAD

**Issue by CJGutz** [hackerspace-ntnu/statutter#11]
Slik beskrives bruken av fullmakten
> Stemmeretten kan gis videre ved skriftlig fullmakt; denne kontrolleres av tellekorpset på generalforsamlingen.

Jeg vil legge til en setning under som beskriver at en person kan bare få et gitt antall fullmakter.
> Et medlem kan bare få 1 fullmakt fra et annet medlem

**Comment by torsteinnh** [comment]
Grense lagt til i siste revisjon.
