### ISSUE TITLE
Hva skjer dersom Devops eller Labops ikke har medlemmer

### ISSUE THREAD

**Issue by Joakim-droid** [hackerspace-ntnu/statutter#12]
“If one of the permanent groups (DevOps and LabOps) has no members, their tasks will be taken over by the management, until the group has members again. A custodian for the group will be appointed by the board, and will manage their vote until the group has members again.”
Proposed by Kristian Skåland

Norsk:

Dersom en av de permanente gruppene (Devops og LabOps) ikke har noen medlemmer, vil oppgavene falle på Ledelsen, fram til gruppen får medlemmer igjen. En representant for gruppa vil bli oppnevnt av styret og vil disponere stemmen til gruppa fram til gruppen får medlemmer igjen.
Forslag fra Kristian Skåland 

Styremøte 27.04.2023

**Comment by torsteinnh** [comment]
Lagt til ved sist årsmøte.
