### ISSUE TITLE
Opptak

### ISSUE THREAD

**Issue by Davidspilde** [hackerspace-ntnu/statutter#15]
Endre "Opptak skal som hovedregel avholdes hver høst. Ekstra opptak kan avholdes på våren om det
er ønskelig." til at det er løpende opptak

**Comment by Davidspilde** [comment]
"Det er løpende opptak, dette innebærer at studenter kan legge inn søknad for medlemskap i Hackerspace når som helst."

**Comment by torsteinnh** [comment]
Lagt til ved sist årsmøte.
